AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - _site/**/*
    - vendor/**/*

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false
