#!/bin/sh

set -e

echo "copy licenses"

mkdir raw
for file in _licenses/*.txt; do cp "$file" "raw/$(basename "$file" .txt)"; done

echo "bundling installin'"
gem install bundler
bundle install

echo
echo "You're all set. Just run script/server and you can play license roulette!"
