#!/bin/sh

set -e

echo "bundling installin'"
gem install bundler
bundle install

echo "npm installin'"
npm install coffee-script

echo
echo "You're all set. Just run script/server and you can play license roulette!"