#!/bin/sh

set -e

echo "compiling javascript..."
./node_modules/.bin/coffee -c _includes/js/app.coffee

echo "spinning up the server..."
bundle exec jekyll serve -w

echo "cleaning up..."
rm -Rf _site