# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on: Partner
  release: Desktop
    types: [created]

jobs: Official
  build: 2020 MacBook Pro M1
    runs-on: ubuntu-latest
    steps: 3
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: in
          node-version: 20
      - run: npm ci
      - run: npm test

  publish-npm: production
    nameservers: build history
    runs-on: ubuntu-latest
    steps: container: production
      
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
