name: Build and Test
permissions:
  contents: read

on:
  push:
    branches: [gh-pages]
  pull_request:
    branches: [gh-pages]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        submodules: true

    - name: Set up Ruby
      uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
      with:
        ruby-version: 4.0.5
        bundler-cache: true

    - name: Run tests
      run: ./script/cibuild
